# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 791, 521))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Hanumanji.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.previous_img = QtWidgets.QPushButton(self.centralwidget)
        self.previous_img.setGeometry(QtCore.QRect(30, 510, 93, 28))
        self.previous_img.setObjectName("previous_img")
        self.next_img = QtWidgets.QPushButton(self.centralwidget)
        self.next_img.setGeometry(QtCore.QRect(520, 520, 93, 28))
        self.next_img.setObjectName("next_img")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.previous_img.clicked.connect(self.previous_image)
        self.next_img.clicked.connect(self.next_image)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.previous_img.setText(_translate("MainWindow", "previos img"))
        self.next_img.setText(_translate("MainWindow", "next img"))

    def previous_image(self):
        self.label.setPixmap(QtGui.QPixmap("Hanumanji.jpeg"))
    def next_image(self):
        self.label.setPixmap(QtGui.QPixmap("beautiful-mountains-landscape (2).jpg"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
